apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: basket
  name: basket
spec:
  ports:
  - port: 80
  selector:
    app: eshop
    component: basket
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: basket-data
  name: basket-data
spec:
  ports:
  - port: 6379
  selector:
    app: eshop
    component: basket-data
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: basket-data
spec:
  paused: true
  template:
    metadata:
      labels:
        app: eshop
        component: basket-data
    spec:
      containers:
      - name: basket-data
        image: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: basket
spec:
  paused: true
  template:
    metadata:
      labels:
        app: eshop
        component: basket
    spec:
      containers:
      - name: basket
        image: eshop/basket.api
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /basket-api
        - name: ConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: BasketRedisConStr
        - name: EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: BasketBus
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Instrumentation_Key             
        - name: IdentityUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: IdentityUrl
        - name: OrchestratorType
          value: 'K8S'
        ports:
        - containerPort: 80
        # readinessProbe:
        #   httpGet:
        #     path: /hc
        #     port: 80
        #     scheme: HTTP 
        #   initialDelaySeconds: 5
        #   periodSeconds: 10 
        # livenessProbe:
        #   httpGet:
        #     path: /hc
        #     port: 80
        #     scheme: HTTP 
        #   initialDelaySeconds: 60
        #   periodSeconds: 10                 
      imagePullSecrets:
      - name: registry-key
---