apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: locations
  name: locations
spec:
  ports:
  - port: 80
  selector:
    app: eshop
    component: locations
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locations
spec:
  paused: true
  template:
    metadata:
      labels:
        app: eshop
        component: locations
    spec:
      containers:
      - name: locations
        image: eshop/locations.api
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /locations-api
        - name: ConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: LocationsNoSqlDb
        - name: Database
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: LocationsNoSqlDbName
        - name: AzureServiceBusEnabled
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: UseAzureServiceBus
        - name: EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: LocationsBus
        - name: IdentityUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: IdentityUrl
        - name: IdentityUrlExternal
          valueFrom:
           configMapKeyRef:
             name: urls
             key: IdentityUrl   
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Instrumentation_Key
        - name: UseLoadTest
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: EnableLoadTest
        - name: OrchestratorType
          value: 'K8S'          
        ports:
        - containerPort: 80
        # readinessProbe:
        #   httpGet:
        #     path: /hc
        #     port: 80
        #     scheme: HTTP 
        #   initialDelaySeconds: 5
        #   periodSeconds: 10 
        # livenessProbe:
        #   httpGet:
        #     path: /hc
        #     port: 80
        #     scheme: HTTP 
        #   initialDelaySeconds: 60
        #   periodSeconds: 10      
      imagePullSecrets:
      - name: registry-key
---