apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: ordering
  name: ordering
spec:
  ports:
  - port: 80
  selector:
    app: eshop
    component: ordering
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ordering
spec:
  paused: true
  template:
    metadata:
      labels:
        app: eshop
        component: ordering
    spec:
      containers:
      - name: ordering
        image: eshop/ordering.api
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /ordering-api
        - name: ConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: OrderingSqlDb
        - name: EventBusConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: OrderingBus
        - name: AzureServiceBusEnabled
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: UseAzureServiceBus
        - name: IdentityUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: IdentityUrl
        - name: CheckUpdateTime
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: GracePeriodManager_CheckUpdateTime
        - name: GracePeriodTime
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: GracePeriodManager_GracePeriodTime  
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Instrumentation_Key
        - name: UseLoadTest
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: EnableLoadTest
        - name: OrchestratorType
          # value: 'K8S'           
        ports:
        - containerPort: 80
        # readinessProbe:
        #   httpGet:
        #     path: /hc
        #     port: 80
        #     scheme: HTTP 
        #   initialDelaySeconds: 5
        #   periodSeconds: 10 
        # livenessProbe:
        #   httpGet:
        #     path: /hc
        #     port: 80
        #     scheme: HTTP 
        #   initialDelaySeconds: 60
        #   periodSeconds: 10      
      imagePullSecrets:
      - name: registry-key
---