apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: webmvc
  name: webmvc
spec:
  ports:
  - port: 80
  selector:
    app: eshop
    component: webmvc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webmvc
spec:
  paused: true
  template:
    metadata:
      labels:
        app: eshop
        component: webmvc
    spec:
      containers:
      - name: webmvc
        image: eshop/webmvc
        imagePullPolicy: Always
        env:
        - name: PATH_BASE
          value: /webmvc
        - name: DPConnectionString
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: keystore
        - name: IsClusterEnv
          value: 'True'
        - name: BasketUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: MvcClientBasketUrl
        - name: CallBackUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: MvcClientExternalUrl
        - name: LocationsUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: MvcClientLocationsUrl
        - name: CatalogUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: MvcClientCatalogUrl
        - name: IdentityUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: IdentityUrl
        - name: OrderingUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: MvcClientOrderingUrl
        - name: MarketingUrl
          valueFrom:
           configMapKeyRef:
             name: urls
             key: MvcClientMarketingUrl 
        - name: BasketUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: BasketHealthCheckUrl        
        - name: CatalogUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: CatalogHealthCheckUrl
        - name: IdentityUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: IdentityHealthCheckUrl
        - name: OrderingUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: OrderingHealthCheckUrl
        - name: MarketingUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: MarketingHealthCheckUrl  
        - name: PaymentUrlHC
          valueFrom:
           configMapKeyRef:
             name: urls
             key: PaymentHealthCheckUrl  
        - name: ApplicationInsights__InstrumentationKey
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: Instrumentation_Key
        - name: UseLoadTest
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: EnableLoadTest
        - name: OrchestratorType
          value: 'K8S'        
        ports:
        - containerPort: 80
        # readinessProbe:
        #   httpGet:
        #     path: /hc
        #     port: 80
        #     scheme: HTTP 
        #   initialDelaySeconds: 5
        #   periodSeconds: 10 
        # livenessProbe:
        #   httpGet:
        #     path: /hc
        #     port: 80
        #     scheme: HTTP 
        #   initialDelaySeconds: 60
        #   periodSeconds: 10      
      imagePullSecrets:
      - name: registry-key
---
